### ISSUE TITLE
Focus crash

### ISSUE THREAD

**Issue by Dayyer1** [Advanced-Thaumaturgy2/Advanced-Thaumaturgy2#1]
On the MCForum, I was told to take some steps and try to reproduce the crash, (hover over foci without AT installed, which did not end in a crash) and I have had the same problem, hovering over a Thaumic Horizons focus. (I've tried hovering over different foci. It only happens with Thaumic Horizon ones.)

https://www.dropbox.com/s/rpv04yn9dd5ykji/crash-2016-11-18_17.09.54-client.txt?dl=0

Thanks.

**Comment by MonzterAssassin** [comment]
Please reproduce this crash with only the mods affected. Are you using the newest versions of the mods:
Thaumcraft
AT2
Thaumic Horizons?

When you produce this crash with the affected / suspected mods alone it makes it easier to note that it it ONLY the affected mods and not another mod.

**Comment by MonzterAssassin** [comment]
Also could you please post the full forge log (or a link to it preferably)

**Comment by MonzterAssassin** [comment]
On testing it for myself (with only those three mods installed (AT2, Thaumic Horizons, and Thaumcraft) with the latest versions, I was unable to reproduce this crash. I hovered over foci in my inventory (all of them, had a bottomless pouch, and random conbinations of foci) and all of them in the focus selection of a wand, as that was what the crash eluded to. There was no way to produce this crash, the mod responsible for this crash is NOT among the three you listed. Issue closed.

Edit: I even went and installed Thaumic bases, which you said was included on the forums, and it still won't crash, no matter what I do with your steps.

**Comment by Dayyer1** [comment]
Ok. Thank you for your help.
Did you test it with r13? I downloaded r14, but didn't attempt a crash with it yet. (A pretty weird thing to say.)
I'll find out what it is eventually. (or just not use the foci. I mainly like Thaumic Horizons for the self-infusions.)

**Comment by MonzterAssassin** [comment]
Indeed I used r13, from the curse download, didn't realize you were using the jenkins build (but they're the same)

**Comment by ToFam** [comment]
Try disabling the Void Cage Focus in the AT2 config and see if the problem persists.
