### ISSUE TITLE
Debug Test Notes

### ISSUE THREAD

**Issue by spannerman79** [Advanced-Thaumaturgy2/Advanced-Thaumaturgy2#9]
This was brought up in the discord text channel by Fleynic#2915 (Discord ID)

Referencing 
![capture](https://cloud.githubusercontent.com/assets/7542384/22720778/ffbcbc32-ee00-11e6-9a8b-af45196353d0.PNG)

Suggestion: Is it possible to hide this behind a FML debug switch or to hide it behind a FML dev environment switch?

**Comment by MonzterAssassin** [comment]
Finally fixed this. Just got preoccupied. Now it will only appear in Alpha or possibly beta builds, but no longer official releases.

**Comment by spannerman79** [comment]
Reference: Fixed via https://github.com/Advanced-Thaumaturgy2/Advanced-Thaumaturgy2/commit/a6c6692e104dffed2254e7c2c078cdc7393d1d58
